# Generated by Django 2.0.5 on 2018-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_package_packageprice_packageterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
